services:
    pim_import_export.form.jobInstance:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_import_export_jobInstance_type_form'
            - 'Pim\Bundle\ImportExportBundle\Form\Type\JobInstanceFormType'
