services:
    # Form
    pim_enrich.form.attribute:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_attribute_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\AttributeType'

    pim_enrich.form.attribute_group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_attributegroup_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\AttributeGroupType'

    pim_enrich.form.family:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_family_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\FamilyType'

    pim_enrich.form.currency:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_currency_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\CurrencyType'

    pim_enrich.form.group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_group_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\GroupType'

    pim_enrich.form.variant_group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_variant_group_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\VariantGroupType'

    pim_enrich.form.group_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_grouptype_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\GroupTypeType'

    pim_enrich.form.association_type:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_enrich_associationtype_form'
            - 'Pim\Bundle\EnrichBundle\Form\Type\AssociationTypeType'

    pim_enrich.form.type.async_select:
        class: Pim\Bundle\EnrichBundle\Form\Type\AsyncSelectType
        arguments:
            - '@router'
            - '@pim_enrich.factory.transformer.identifiable_model'
        tags:
            - { name: form.type, alias: pim_async_select }

    pim_enrich.form.type.export_select_family:
        class: Pim\Bundle\EnrichBundle\Form\Type\SelectFamilyType
        arguments:
            - '@router'
        tags:
            - { name: form.type, alias: select_family_type }
