services:
    pim_comment.form.attribute_group:
        class: 'Symfony\Component\Form\Form'
        factory: 'form.factory:createNamed'
        arguments:
            - 'pim_comment_comment_form'
            - 'Pim\Bundle\CommentBundle\Form\Type\CommentType'
